// SUPERSEDED. Requires the Codex-only @oai/artifact-tool and will not run outside
// that runtime. Kept for provenance; build_macro_free_interface.py is the supported
// builder and produces the same workbook from the same workbench-schema.json.
import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const wb=Workbook.create(),navy='#18344C',amber='#FFF4CF';
const schemas=JSON.parse(await fs.readFile('workbench-schema.json','utf8'));
function page(name,widths){const s=wb.worksheets.add(name);s.showGridLines=false;widths.forEach((w,i)=>s.getCell(0,i).format.columnWidth=w);s.getRange('A1:J60').format.font={name:'Arial',size:11,color:navy};return s;}
function text(s,c,v){s.getRange(c).values=[[v]];}
function title(s,v){text(s,'B2',v);s.getRange('B2').format.font={name:'Arial',size:16,bold:true,color:navy};s.getRange('B2:G2').format.rowHeight=30;}
function field(s,r,l,v=''){text(s,`B${r}`,l);text(s,`C${r}`,v);s.getRange(`C${r}`).format={fill:amber,numberFormat:'@',wrapText:true,verticalAlignment:'top'};s.getRange(`B${r}:G${r}`).format.rowHeight=27;}
const d=page('Review Desk',[3,23,59,3,27,3,76]);title(d,'Annotation workbench');text(d,'C3','Start: load a note. Yellow cells are editable.');
for(const [r,l,v] of [[4,'Claim number',''],[5,'Note ID',''],[6,'Source version',''],[7,'Reviewer',''],[9,'Entry kind','entity'],[10,'Exact source quote',''],[11,'Occurrence (1, 2...)','1'],[12,'Entity reference',''],[13,'Display name',''],[14,'Entity type',''],[15,'Reference form',''],[16,'Field kind',''],[17,'Field value',''],[18,'Second entity',''],[19,'Optional open label',''],[20,'Context / reason','']])field(d,r,l,v);
d.getRange('C10').format.rowHeight=90;d.getRange('C20').format.rowHeight=65;
for(const [c,values] of [['C9',['entity','reference','field','context','statement','uncertain']],['C15',['name','alias','pronoun','description']],['C16',['entity_name','address','city','state','zip_code','phone','TIN','other']]])d.getRange(c).dataValidation={rule:{type:'list',values}};
text(d,'B22','Saved state');text(d,'C22','Not wired. Follow Instructions to activate buttons.');d.getRange('C22').format.wrapText=true;
text(d,'B24','Attestation');text(d,'C24','I confirm that I have read enough of the source note to validate this entry, its supporting evidence, and its links to other entities. I have corrected any errors I identified.');d.getRange('C24').format={wrapText:true,rowHeight:85};
text(d,'G4','Note text and source evidence');text(d,'G5','Load a note to read it here. Next text page reaches every passage.');d.getRange('G5:G20').format={wrapText:true,verticalAlignment:'top',fill:'#EDF3F7'};
text(d,'G23','Entities in this claim');text(d,'G24','Choose entity lists current claim entities.');
for(const [c,l] of [['E4','Select note'],['E5','New manual entry'],['E7','Load next AI draft'],['E9','Attest & Save'],['E11','Save draft'],['E12','Previous entry'],['E13','Next reviewed entry'],['E15','Delete entry'],['E17','Choose entity'],['E18','Locate evidence'],['E20','Complete note'],['E22','Previous text page'],['E23','Next text page'],['E25','Watchlist review']]){text(d,c,l);d.getRange(c).format={fill:navy,font:{name:'Arial',size:11,color:'#FFFFFF',bold:true},wrapText:true,rowHeight:30};}
const n=page('Notes',[3,23,75,3,28]);title(n,'Add claim notes');field(n,4,'Claim number');field(n,5,'Note ID');field(n,6,'Reading order','1');text(n,'C8','Copy the complete note in Notepad. Click Paste whole note. Do not paste a long note into a single cell.');n.getRange('C8').format={wrapText:true,rowHeight:55};text(n,'E4','Paste whole note');text(n,'E6','Import TXT files');text(n,'E8','Open selected note');
const ai=page('AI Instructions',[3,24,110]);title(ai,'Optional AI drafting');const prompt=await fs.readFile('COPILOT-PROMPT.md','utf8');prompt.split('\n').filter(x=>x.trim()).forEach((l,i)=>{text(ai,`C${i+4}`,l);ai.getRange(`C${i+4}`).format={wrapText:true,rowHeight:Math.max(28,Math.ceil(l.length/110)*18)};});
const a=page('AI Analysis Input',[3,24,105]);title(a,'AI analysis for current note');for(const [r,l,v] of [[4,'Run label',''],[5,'Processed parts',''],[6,'Run complete?','no'],[7,'Brief analysis','']])field(a,r,l,v);a.getRange('C7').format.rowHeight=100;text(a,'C9','Save queue snapshot archives analysis for the current note. Analysis retention: last five distinct notes pasted.');a.getRange('C9').format={wrapText:true,rowHeight:45};
const q=page('AI Queue',[3]);title(q,'AI proposals');text(q,'B3','Run SaveQueueSnapshot after Copilot finishes. Drafts are not accepted annotations.');
const w=page('Watchlist Desk',[3,23,60,3,25,3,76]);title(w,'Watchlist identity review');for(const [r,l] of [[4,'Client row ID'],[5,'Identity decision'],[6,'Reason / evidence']])field(w,r,l);w.getRange('C6').format.rowHeight=100;w.getRange('C5').dataValidation={rule:{type:'list',values:['same_entity','different_entity','insufficient_evidence']}};text(w,'E4','Load next pair');text(w,'E6','Save decision');text(w,'E8','Import client output');text(w,'G4','System record and watchlist record');
const ins=page('Instructions',[3,24,115]);title(ins,'Start here');
const lines=['Save a copy as Excel Macro-Enabled Workbook (.xlsm). Keep this original blank template.','Alt+F11 > File > Import File: import every supplied .bas. Paste ThisWorkbook.txt into the ThisWorkbook code window.','Alt+F8 > SetupWorkbench > Run creates the buttons. No manual shape wiring.','Notes: enter IDs, copy the full note, then Paste whole note. Or import UTF-8 TXT files named CLAIM_NOTE.txt.','Review Desk: choose entry kind, paste exact evidence, select occurrence and fill relevant fields. Choose entity lists accepted entities.','Attest & Save validates and saves. Save draft preserves unfinished work. Manual entry needs no Copilot.','Optional AI: follow AI Instructions. SaveQueueSnapshot validates drafts, then Load next AI draft fills the form.','Previous entry restores your latest revision. Changed entries require new attestations; Delete preserves history.','Complete note requires reading all text, adding missing annotations and resolving drafts. Watchlist review follows.','Only analysis for the last five distinct notes pasted is retained. Sources, pending queues and accepted records persist.','One SME writer per workbook. Do not edit with Copilot while macros save. Do not edit backend tables.','Keep older workbooks untouched. Read WIRE-UP-IN-EXCEL.md before bringing historical annotations into this layout.','Licensed Windows Excel runtime qualification is still required. Macros do not run in Excel for the web.'];lines.forEach((l,i)=>{text(ins,`B${4+i}`,`${i+1}.`);text(ins,`C${4+i}`,l);ins.getRange(`C${4+i}`).format={wrapText:true,rowHeight:45};});
function col(i){let s='';while(i){i--;s=String.fromCharCode(65+i%26)+s;i=Math.floor(i/26)}return s;}
for(const [name,def] of Object.entries(schemas)){const s=name==='Notes'?n:name==='AI Queue'?q:page(name,[3]);const row=name==='Notes'?12:name==='AI Queue'?5:1;s.getRangeByIndexes(row-1,0,1,def.headers.length).values=[def.headers];s.tables.add(`A${row}:${col(def.headers.length)}${row+1}`,true,def.table);s.getRangeByIndexes(row-1,0,1,def.headers.length).format={fill:navy,font:{name:'Arial',size:11,bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:42};s.getRangeByIndexes(row,0,10,def.headers.length).setNumberFormat('@');if(name!=='Notes'){def.headers.forEach((h,i)=>s.getCell(0,i).format.columnWidth=/text|quote|reason|analysis|value|label/.test(h)?48:22);s.freezePanes.freezeRows(row);}}
wb.recalculate();await fs.mkdir('macro-free-preview',{recursive:true});
for(const name of ['Review Desk','Notes','AI Instructions','AI Queue','AI Analysis Input','Watchlist Desk','Instructions',...Object.keys(schemas).filter(x=>!['Notes','AI Queue'].includes(x))]){const range=name==='Review Desk'?'B2:G25':name==='Notes'?'B2:E14':name==='AI Instructions'?'B2:C12':name==='Instructions'?'B2:C16':name==='Watchlist Desk'?'B2:G10':name==='AI Analysis Input'?'B2:C9':name==='AI Queue'?'A5:F8':'A1:F3';const b=await wb.render({sheetName:name,range,scale:1,format:'png'});await fs.writeFile(`macro-free-preview/${name.replaceAll(' ','-')}.png`,new Uint8Array(await b.arrayBuffer()));}
const checks=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!',options:{useRegex:true,maxResults:50}});await fs.writeFile('Entity-Gold-Review-Macro-Free.checks.ndjson',checks.ndjson);await(await SpreadsheetFile.exportXlsx(wb)).save('Entity-Gold-Review-Macro-Free.xlsx');console.log('Built workbook; rendered every sheet; checked formula errors.');
